import { OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormulairesService, ChampPaletteItem } from '../../services/formulaires.service';
import { ServicesService } from '../../services/services.service';
import { ActiviteService } from '../../services/activite.service';
import { Formulaire, FormulaireChamp, TypeChamp, ServiceInstitution } from '../../models/provider.model';
type EtapeType = 'infos' | 'champs' | 'finalisation';
export declare class FormBuilderComponent implements OnInit {
    private formulairesService;
    private servicesService;
    private activiteService;
    private route;
    private router;
    palette: ChampPaletteItem[];
    services: ServiceInstitution[];
    etape: EtapeType;
    nbColonnes: number;
    showApercu: boolean;
    formulaire: Formulaire;
    description: string;
    champSelectionne: FormulaireChamp | null;
    draggedType: TypeChamp | null;
    draggedExistingIndex: number | null;
    dragOverIndex: number | null;
    isSaving: boolean;
    notification: {
        message: string;
        type: 'success' | 'error';
    } | null;
    showQuickAdd: boolean;
    nouveauChampNom: string;
    constructor(formulairesService: FormulairesService, servicesService: ServicesService, activiteService: ActiviteService, route: ActivatedRoute, router: Router);
    ngOnInit(): void;
    getServiceNom(serviceId: number): string;
    allerAuxChamps(): void;
    retournerInfos(): void;
    allerVersFinalisation(): void;
    retournerAuxChamps(): void;
    ouvrirAjoutRapide(): void;
    fermerAjoutRapide(): void;
    ajouterChampRapide(): void;
    private genererCodeChamp;
    onPaletteDragStart(type: TypeChamp): void;
    onChampDragStart(index: number, event: DragEvent): void;
    onChampDragEnd(): void;
    onDragOver(index: number, event: DragEvent): void;
    onDrop(index: number, event: DragEvent): void;
    onCanvasDropZone(event: DragEvent): void;
    reordonnerChamps(): void;
    deplacerChamp(index: number, direction: number): void;
    changerNbColonnes(nb: number): void;
    ouvrirApercu(): void;
    fermerApercu(): void;
    selectionnerChamp(champ: FormulaireChamp): void;
    supprimerChamp(champ: FormulaireChamp, event: Event): void;
    dupliquerChamp(champ: FormulaireChamp, event: Event): void;
    ajouterOption(): void;
    supprimerOption(index: number): void;
    iconePourType(type: TypeChamp): string;
    labelPourType(type: TypeChamp): string;
    enregistrer(publier?: boolean): void;
    afficherNotification(message: string, type: 'success' | 'error', dureeMs?: number): void;
}
export {};
//# sourceMappingURL=form-builder.component.d.ts.map