import { EventEmitter, OnInit, OnDestroy, OnChanges, SimpleChanges } from '@angular/core';
export declare class UsersDeleteComponent implements OnInit, OnDestroy, OnChanges {
    isOpen: boolean;
    user: any;
    isLoading: boolean;
    error: string;
    success: string;
    close: EventEmitter<void>;
    confirm: EventEmitter<void>;
    showOtpStep: boolean;
    otpCode: string;
    otpError: string;
    otpAttempts: number;
    maxOtpAttempts: number;
    isOtpLocked: boolean;
    otpLockTimer: number;
    otpTimer: number;
    private otpTimerInterval;
    private lockTimerInterval;
    otpVerified: boolean;
    showDeleteStep: boolean;
    deleteReason: string;
    confirmText: string;
    reasonOptions: string[];
    constructor();
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    generateAndSendOtp(): void;
    private startOtpTimer;
    private startLockTimer;
    private clearOtpTimer;
    private clearLockTimer;
    private clearAllTimers;
    verifyOtp(): void;
    resendOtp(): void;
    onConfirmDelete(): void;
    onClose(): void;
    goBackToOtp(): void;
    private resetForm;
    getInitials(firstName: string, lastName: string): string;
    getAvatarColor(id: string): string;
    getRoleLabel(role: string): string;
    getStatusLabel(status: string): string;
    getStatusClass(status: string): string;
    getOtpRemainingTime(): string;
    getLockRemainingTime(): string;
}
//# sourceMappingURL=users-delete.component.d.ts.map