interface CardData {
    id: string;
    numero: string;
    uid: string;
    typeCarte: 'parent' | 'enfant';
    utilisateur: string;
    userId: string;
    solde: number;
    statut: 'active' | 'bloquee' | 'desactivee' | 'expiree' | 'inactive';
    dateEmission: string;
    dateExpiration: string;
}
interface Toast {
    id: number;
    message: string;
    type: 'success' | 'danger' | 'info' | 'warning';
}
export declare class CardsSettingsComponent {
    readonly title = "Gestion des Cartes";
    readonly icon = "\uD83D\uDCB3";
    readonly pageSize = 10;
    activeTab: 'cartes' | 'stocks';
    private currentPages;
    searchTerm: string;
    filterStatut: string;
    filterType: string;
    private cartes;
    private historique;
    private toastSeq;
    modalOpen: boolean;
    selectedCard: CardData | null;
    pinModalOpen: boolean;
    pinActionType: string;
    pinData: any;
    pinError: boolean;
    actionModalOpen: boolean;
    actionModalTitle: string;
    actionModalType: string;
    formData: any;
    historiqueCartes: any[];
    toasts: Toast[];
    constructor();
    private initializeData;
    getFilteredCartes(): CardData[];
    getFilteredStock(): CardData[];
    onSearchChange(): void;
    onFilterChange(): void;
    getTotalCartes(): number;
    getCartesByStatut(statut: CardData['statut']): CardData[];
    getCartesParent(): CardData[];
    getCartesEnfant(): CardData[];
    getCartesInactives(): CardData[];
    getAllCartes(): CardData[];
    getStockTotal(): number;
    getTotalGeneral(): number;
    getStatutLabel(statut: string): string;
    getPaginatedFilteredCartes(): CardData[];
    getPaginatedFilteredStock(): CardData[];
    getTotalFilteredPages(type: string): number;
    getCurrentPage(type: string): number;
    nextPage(type: string): void;
    previousPage(type: string): void;
    setActiveTab(tab: 'cartes' | 'stocks'): void;
    private pendingAction;
    openCardAction(card: CardData, action: string): void;
    onPinChange(): void;
    closePinModal(): void;
    confirmPin(): void;
    getActionIcon(): string;
    openAction(actionId: string): void;
    openCardDetails(card: CardData): void;
    openCardHistory(card: CardData): void;
    private generateFakeHistory;
    getActionClass(action: string): string;
    getMontantClass(montant: string): string;
    private getActionTitle;
    confirmAction(): void;
    private emettreCarte;
    private associerCarte;
    private desassocierCarte;
    private activerCarte;
    private desactiverCarte;
    private bloquerCarte;
    private debloquerCarte;
    private renouvelerCarte;
    private reinitialiserPin;
    private detruireCarte;
    exportExcel(): void;
    exportExcelStock(): void;
    exportHistoryExcel(): void;
    printList(): void;
    printStock(): void;
    printHistory(): void;
    printCardDetail(): void;
    closeModal(): void;
    closeActionModal(): void;
    toast(message: string, type?: Toast['type']): void;
    dismissToast(id: number): void;
}
export {};
//# sourceMappingURL=cards-settings.component.d.ts.map