import { OnInit, OnDestroy } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ServicePublic, Utilisateur, Categorie, TypeRNF, PaiementRNF } from '../../models/service-public.model';
import { ServicesPublicsService } from '../../services/services-publics.service';
export interface Activite {
    id: number;
    type: 'paiement' | 'utilisateur' | 'categorie' | 'type-rnf' | 'system';
    title: string;
    user: string;
    date: Date;
    details?: string;
}
export declare class ServicesPublicsDetailComponent implements OnInit, OnDestroy {
    private route;
    private router;
    private servicesPublicsService;
    service: ServicePublic | undefined;
    loading: boolean;
    notFound: boolean;
    activeModule: string;
    usersCurrentPage: number;
    usersItemsPerPage: number;
    usersTotalPages: number;
    categoriesCurrentPage: number;
    categoriesItemsPerPage: number;
    categoriesTotalPages: number;
    typesRNFCurrentPage: number;
    typesRNFItemsPerPage: number;
    typesRNFTotalsPages: number;
    paiementsCurrentPage: number;
    paiementsItemsPerPage: number;
    paiementsTotalPages: number;
    activitiesCurrentPage: number;
    activitiesItemsPerPage: number;
    activityTypeFilter: string;
    allActivities: Activite[];
    private activityInterval;
    private activityCounter;
    exportLoading: boolean;
    showNotification: boolean;
    notificationMessage: string;
    notificationType: 'success' | 'error' | 'info';
    viewingTypeRNF: TypeRNF | null;
    readonly Math: Math;
    private activityTypes;
    constructor(route: ActivatedRoute, router: Router, servicesPublicsService: ServicesPublicsService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    initPagination(): void;
    initActivities(): void;
    private getRandomItem;
    generateInitialActivities(): Activite[];
    startActivityRealtime(): void;
    stopActivityRealtime(): void;
    addNewActivity(): void;
    getRecentActivities(limit?: number): Activite[];
    getAllActivitiesCount(): number;
    get filteredActivities(): Activite[];
    get activitiesTotalPages(): number;
    get paginatedActivities(): Activite[];
    setActivityFilter(type: string): void;
    changeActivitiesPage(page: number): void;
    getActivitiesPaginationPages(): number[];
    getActivityTypeLabel(type: string): string;
    switchModule(module: string): void;
    getTotalItems(): number;
    get paginatedUtilisateurs(): Utilisateur[];
    get paginatedCategories(): Categorie[];
    get paginatedTypesRNF(): TypeRNF[];
    get paginatedPaiements(): PaiementRNF[];
    changeUsersPage(page: number): void;
    getUsersPaginationPages(): number[];
    changeCategoriesPage(page: number): void;
    getCategoriesPaginationPages(): number[];
    changeTypesRNFPage(page: number): void;
    getTypesRNFPaginationPages(): number[];
    changePaiementsPage(page: number): void;
    getPaiementsPaginationPages(): number[];
    goBack(): void;
    onEdit(): void;
    onActivate(): void;
    onDeactivate(): void;
    onAddUtilisateur(): void;
    onEditUtilisateur(user: Utilisateur): void;
    onToggleUtilisateur(user: Utilisateur): void;
    onDeleteUtilisateur(user: Utilisateur): void;
    onAddCategory(): void;
    onViewCategory(category: Categorie): void;
    onEditCategory(category: Categorie): void;
    onToggleCategory(category: Categorie): void;
    getCategoryColor(code: string): string;
    onAddTypeRNF(): void;
    onViewTypeRNF(type: TypeRNF): void;
    closeTypeRNFModal(): void;
    onEditTypeRNF(type: TypeRNF): void;
    onToggleTypeRNF(type: TypeRNF): void;
    onAddPaiement(): void;
    getTypeRNFNom(typeRNFId: number): string;
    getSousTypeRNFNom(sousTypeRNFId?: number): string;
    getTotalPaiements(): number;
    exportUsers(): void;
    exportCategories(): void;
    exportTypesRNF(): void;
    exportPaiements(): void;
    private exportData;
    private addActivity;
    getServiceColor(abreviation: string): string;
    closeNotification(): void;
}
//# sourceMappingURL=services-publics-detail.component.d.ts.map