import { OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Agent, SubAgent, Deposit } from '../../models/agent.model';
import { AgentService } from '../../services/agent.service';
export declare class AgentDetailComponent implements OnInit {
    private route;
    private router;
    private agentService;
    agent: Agent | null;
    isLoading: boolean;
    isDarkMode: boolean;
    activeTab: 'profile' | 'mouvements' | 'depots' | 'commissions';
    selectedSubAgent: SubAgent | null;
    showTransactionsModal: boolean;
    movementSearchTerm: string;
    depositSearchTerm: string;
    commissionSearchTerm: string;
    private colorPalette;
    private agentCards;
    constructor(route: ActivatedRoute, router: Router, agentService: AgentService);
    ngOnInit(): void;
    loadTheme(): void;
    toggleTheme(): void;
    loadAgent(id: string): void;
    get filteredAgentsForMovement(): SubAgent[];
    onMovementSearch(event: any): void;
    clearMovementSearch(): void;
    get filteredDeposits(): Deposit[];
    onDepositSearch(event: any): void;
    clearDepositSearch(): void;
    get filteredAgentsForCommission(): SubAgent[];
    onCommissionSearch(event: any): void;
    clearCommissionSearch(): void;
    getColor(id: string, index: number): string;
    getAgentCardNumber(agentId: string): string;
    getTotalSentAmount(agentId: string): number;
    getCommissionReceived(agentId: string): number;
    getInitialsAgent(name: string): string;
    getDepositCardNumber(agentId: string): string;
    getTotalCommissions(): number;
    goBack(): void;
    setTab(tab: 'profile' | 'mouvements' | 'depots' | 'commissions'): void;
    getStatusLabel(status: string): string;
    getStatusClass(status: string): string;
    getTransactionTypeIcon(type: string): string;
    getTransactionTypeLabel(type: string): string;
    getTransactionTypeClass(type: string): string;
    getTransactionStatusLabel(status: string): string;
    getTransactionStatusClass(status: string): string;
    getElectronicStatusClass(status: string): string;
    getElectronicStatusLabel(status: string): string;
    getElectronicTypeLabel(type: string): string;
    getInitials(firstName: string, lastName: string): string;
    getDepositStatusLabel(status: string): string;
    getDepositStatusClass(status: string): string;
    viewSubAgentTransactions(subAgent: SubAgent): void;
    closeTransactionsModal(): void;
}
//# sourceMappingURL=agent-detail.component.d.ts.map