import { OnInit, OnDestroy } from '@angular/core';
import { BilletsService } from '../../services/billets.service';
import { EvenementsService } from '../../services/evenements.service';
import { Billet, StatutBillet, Evenement, VenteHistorique } from '../../models/evenements.model';
import { ToastService } from '../../core/toast.service';
type VueBilletterie = 'TEMPS_REEL' | 'HISTORIQUE';
export declare class BilletterieLiveComponent implements OnInit, OnDestroy {
    private billetsService;
    private evenementsService;
    private toastService;
    vueActive: VueBilletterie;
    billets: Billet[];
    filtered: Billet[];
    evenements: Evenement[];
    filtreEvenement: string;
    filtreStatut: string;
    filtreNumero: string;
    isLoading: boolean;
    currentPage: number;
    pageSize: number;
    billetDetailAffiche: Billet | null;
    historique: VenteHistorique[];
    historiqueFiltre: VenteHistorique[];
    historiqueFiltreEvenement: string;
    historiqueFiltreCategorie: string;
    historiquePage: number;
    historiquePageSize: number;
    isLoadingHistorique: boolean;
    private sub?;
    constructor(billetsService: BilletsService, evenementsService: EvenementsService, toastService: ToastService);
    ngOnInit(): void;
    ngOnDestroy(): void;
    changerVue(vue: VueBilletterie): void;
    chargerHistorique(): void;
    /** Catégories disponibles pour l'événement sélectionné dans l'historique (ou toutes si aucun événement choisi). */
    get categoriesHistoriqueDisponibles(): string[];
    appliquerFiltresHistorique(): void;
    reinitialiserFiltresHistorique(): void;
    get historiqueRevenuTotal(): number;
    get historiqueBilletsTotal(): number;
    get historiqueTotalPages(): number;
    get historiquePagine(): VenteHistorique[];
    changerPageHistorique(page: number): void;
    applyFilters(): void;
    onFiltreChange(): void;
    get totalPages(): number;
    get filteredPagines(): Billet[];
    changePage(page: number): void;
    get reservesCount(): number;
    get payesCount(): number;
    get utilisesCount(): number;
    get revenuTotal(): number;
    formatBIF(v: number): string;
    nomEvenement(id: number): string;
    statutClass(statut: StatutBillet): string;
    statutLabel(statut: StatutBillet): string;
    minutesEcoulees(date: Date): number;
    ouvrirDetail(b: Billet): void;
    fermerDetail(): void;
    confirmerPaiement(b: Billet, event?: Event): void;
    validerEntree(b: Billet, event?: Event): void;
    annulerBillet(b: Billet, event?: Event): void;
}
export {};
//# sourceMappingURL=billetterie-live.component.d.ts.map