import { OnInit } from '@angular/core';
import { BilletsService } from '../../services/billets.service';
import { EvenementsService } from '../../services/evenements.service';
import { Billet, Evenement, Organisateur, Lieu, TypeEvenement, VenteHistorique } from '../../models/evenements.model';
import { ExportUtilsService, ColonneExport, LigneExport } from '../../core/export-utils.service';
type TypeRapportEvenements = 'BILLETS' | 'REVENUS_ORGANISATEURS' | 'EVENEMENTS';
export declare class RapportsEvenementsComponent implements OnInit {
    private billetsService;
    private evenementsService;
    private exportUtils;
    isLoading: boolean;
    billets: Billet[];
    evenements: Evenement[];
    organisateurs: Organisateur[];
    lieux: Lieu[];
    historique: VenteHistorique[];
    typeRapport: TypeRapportEvenements;
    dateDebut: string;
    dateFin: string;
    typeEvenement: '' | TypeEvenement;
    statut: string;
    recherche: string;
    colonnes: ColonneExport[];
    lignes: LigneExport[];
    currentPage: number;
    pageSize: number;
    ligneDetailAffichee: LigneExport | null;
    constructor(billetsService: BilletsService, evenementsService: EvenementsService, exportUtils: ExportUtilsService);
    ngOnInit(): void;
    changerType(type: TypeRapportEvenements): void;
    reinitialiserFiltres(): void;
    private dansPeriode;
    genererRapport(): void;
    nomEvenement(id: number): string;
    nomLieu(id: number): string;
    nomOrganisateur(id: number): string;
    statutLabel(statut: string): string;
    typeLabel(type: TypeEvenement): string;
    private genererRapportBillets;
    private genererRapportOrganisateurs;
    private genererRapportEvenements;
    get totalLignes(): number;
    get montantTotal(): number;
    get totalPages(): number;
    get lignesPaginees(): LigneExport[];
    changePage(page: number): void;
    ouvrirDetailLigne(ligne: LigneExport): void;
    fermerDetailLigne(): void;
    exporterLigneExcel(): void;
    imprimerLigne(): void;
    exporterExcel(): void;
    imprimer(): void;
}
export {};
//# sourceMappingURL=rapports-evenements.component.d.ts.map