import { OnInit } from '@angular/core';
interface ServiceRevenue {
    id: string;
    date: string;
    serviceId: string;
    serviceName: string;
    category: string;
    subCategory: string;
    amount: number;
    reference: string;
    statut: 'collecte' | 'transfert' | 'valide';
    paymentMethod: string;
    description?: string;
    clientName?: string;
    clientId?: string;
}
interface Service {
    id: string;
    key: string;
    name: string;
    icon: string;
    category: string;
    subCategory: string;
    accountNumber: string;
    status: 'actif' | 'inactif';
    fees: number;
    feesType: 'fixe' | 'pourcentage';
    plafond: number;
    commission: number;
    totalRevenue: number;
    transactions: number;
    lastTransaction?: string;
    description?: string;
    requiredDocuments: string[];
    procedure: string[];
    legalText?: string;
}
interface Client {
    id: string;
    name: string;
    email: string;
    phone: string;
    serviceId: string;
    serviceName: string;
    requestDate: string;
    status: 'en_attente' | 'approuve' | 'rejete';
    amount: number;
    reference: string;
    address?: string;
    idNumber?: string;
}
interface Toast {
    id: number;
    message: string;
    type: 'success' | 'danger' | 'info' | 'warning';
}
interface TabItem {
    key: string;
    label: string;
    icon: string;
    count?: number;
}
export declare class ServicesSettingsComponent implements OnInit {
    readonly title = "Gestion des Services RNF";
    readonly icon = "\uD83C\uDFDB";
    readonly pageSize = 100;
    private readonly STORAGE_KEY;
    private toastSeq;
    services: Service[];
    revenues: ServiceRevenue[];
    clients: Client[];
    toasts: Toast[];
    selectedService: Service | null;
    showModal: boolean;
    showDetailModal: boolean;
    showClientModal: boolean;
    showDesactivatePinModal: boolean;
    modalType: string;
    modalTitle: string;
    formData: any;
    showPinModal: boolean;
    pinCode: string;
    desactivatePinCode: string;
    selectedClient: Client | null;
    serviceToDesactivate: Service | null;
    activeTab: string;
    private currentPages;
    tabs: TabItem[];
    categories: any[];
    private clientNames;
    constructor();
    ngOnInit(): void;
    getCurrentDate(): string;
    getRandomDemandeNumber(): string;
    addPinDigit(digit: number): void;
    clearPin(): void;
    addDesactivatePinDigit(digit: number): void;
    clearDesactivatePin(): void;
    confirmPin(): void;
    closePinModal(): void;
    confirmDesactivatePin(): void;
    closeDesactivatePinModal(): void;
    private initializeData;
    private ensureClientsForAllServices;
    private generateRevenues;
    private saveData;
    private loadData;
    getServices(): Service[];
    getServicesByCategory(categoryId: string): Service[];
    getRevenues(): ServiceRevenue[];
    getClients(): Client[];
    getClientsByService(serviceId: string): Client[];
    getRevenuesByService(serviceId: string): ServiceRevenue[];
    getServiceTotalRevenue(serviceId: string): number;
    getServiceTotalRevenueFormatted(serviceId: string): string;
    getServiceClientCount(serviceId: string): number;
    getTotalPages(type: string): number;
    getPaginatedRevenues(): ServiceRevenue[];
    getPaginatedClients(serviceId: string): Client[];
    getTotalClientPages(serviceId: string): number;
    getCurrentPage(type: string): number;
    nextPage(type: string): void;
    prevPage(type: string): void;
    nextClientPage(serviceId: string): void;
    prevClientPage(serviceId: string): void;
    setActiveTab(tab: string): void;
    private updateCounts;
    getTotalRevenues(): number;
    getTotalRevenuesFormatted(): string;
    getActiveServicesCount(): number;
    getServicesByCategoryCount(categoryId: string): number;
    getRevenuesByCategoryId(categoryId: string): number;
    getRevenuesByCategoryIdFormatted(categoryId: string): string;
    getTotalRevenuesByCategory(category: string): string;
    exportToExcel(): void;
    private exportToCSV;
    printServices(): void;
    openClientDetail(client: Client): void;
    closeClientModal(): void;
    approveClient(client: Client): void;
    rejectClient(client: Client): void;
    openDesactivatePinModal(service: Service): void;
    openDetailModal(service: Service): void;
    closeDetailModal(): void;
    getKpiData(): any[];
    getRevenuesByCategory(): any[];
    getRevenuesByServiceList(): any[];
    openServiceModal(service: Service, action: string): void;
    confirmModal(): void;
    closeModal(): void;
    openPinModal(): void;
    toast(message: string, type?: Toast['type']): void;
    dismissToast(id: number): void;
    getStatutLabel(statut: string): string;
    getCategoryIcon(categoryId: string): string;
    getCategoryName(categoryId: string): string;
}
export {};
//# sourceMappingURL=services-settings.component.d.ts.map