import { OnInit, AfterViewInit, ElementRef } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { ReportDummyData } from '../../data/report-dummy.data';
import { ReportDefinition, KpiCard, ChartDataPoint } from '../../models/report.models';
type SortDir = 'asc' | 'desc';
type ReportDataType = 'financial' | 'commissions' | 'trust-account' | 'cash-management' | 'offline-pos' | 'compliance' | 'kyc-users';
export declare class ReportDetailComponent implements OnInit, AfterViewInit {
    private dummy;
    private route;
    private router;
    trendCanvasRef: ElementRef<HTMLCanvasElement>;
    breakdownCanvasRef: ElementRef<HTMLCanvasElement>;
    Math: Math;
    reportDef: ReportDefinition | null;
    reportType: ReportDataType;
    dateFrom: string;
    dateTo: string;
    selectedAgent: string;
    selectedType: string;
    selectedStatus: string;
    agentOptions: {
        id: string;
        name: string;
    }[];
    typeOptions: string[];
    statusOptions: string[];
    kpis: KpiCard[];
    chartTrend: ChartDataPoint[];
    chartBreakdown: ChartDataPoint[];
    private trendChart;
    private breakdownChart;
    tableColumns: {
        key: string;
        label: string;
        sortable: boolean;
        format?: string;
    }[];
    allRows: any[];
    filteredRows: any[];
    sortColumn: string;
    sortDir: SortDir;
    currentPage: number;
    pageSize: number;
    totalPages: number;
    hoveredRowIndex: number | null;
    exporting: boolean;
    constructor(dummy: ReportDummyData, route: ActivatedRoute, router: Router);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    private loadReport;
    private loadFinancial;
    private loadCommissions;
    private loadTrustAccount;
    private loadCashManagement;
    private loadOffline;
    private loadCompliance;
    private loadKyc;
    private drawCharts;
    private destroyCharts;
    private drawTrendChart;
    private drawBreakdownChart;
    applyFilters(): void;
    resetFilters(): void;
    setSort(col: string): void;
    private sortData;
    getSortIcon(col: string): string;
    get pagedRows(): any[];
    prevPage(): void;
    nextPage(): void;
    getPageNumbers(): number[];
    exportCSV(): void;
    exportPDF(): void;
    formatCurrency(v: number): string;
    formatDate(v: Date): string;
    getStatusClass(status: string): string;
    formatTrendValue(v: number): string;
    goBack(): void;
}
export {};
//# sourceMappingURL=report-detail.component.d.ts.map