export declare enum Permission {
    USER_CREATE = "USER_CREATE",
    USER_READ = "USER_READ",
    USER_UPDATE = "USER_UPDATE",
    USER_DELETE = "USER_DELETE",
    USER_SUSPEND = "USER_SUSPEND",
    USER_ACTIVATE = "USER_ACTIVATE",
    ROLE_CREATE = "ROLE_CREATE",
    ROLE_READ = "ROLE_READ",
    ROLE_UPDATE = "ROLE_UPDATE",
    ROLE_DELETE = "ROLE_DELETE",
    ROLE_ASSIGN = "ROLE_ASSIGN",
    PERMISSION_READ = "PERMISSION_READ",
    PERMISSION_ASSIGN = "PERMISSION_ASSIGN",
    PERMISSION_REVOKE = "PERMISSION_REVOKE",
    DASHBOARD_VIEW = "DASHBOARD_VIEW",
    SYSTEM_SETTINGS = "SYSTEM_SETTINGS",
    AUDIT_LOG_VIEW = "AUDIT_LOG_VIEW"
}
export declare const PermissionLabels: Record<Permission, string>;
//# sourceMappingURL=permission.enum.d.ts.map