import { OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Categorie, Frais, DocumentRequis } from '../../../models/service-public.model';
import { ServicesPublicsService } from '../../../services/services-publics.service';
export declare class CategoryDetailComponent implements OnInit {
    private route;
    private router;
    private servicesPublicsService;
    category: Categorie | undefined;
    serviceId: number;
    loading: boolean;
    notFound: boolean;
    fraisCurrentPage: number;
    fraisItemsPerPage: number;
    fraisTotalPages: number;
    documentsCurrentPage: number;
    documentsItemsPerPage: number;
    documentsTotalPages: number;
    activeTab: string;
    showNotification: boolean;
    notificationMessage: string;
    notificationType: 'success' | 'error' | 'info';
    fraisModalOpen: boolean;
    fraisModalMode: 'add' | 'edit';
    fraisForm: any;
    private editingFraisId;
    documentModalOpen: boolean;
    documentModalMode: 'add' | 'edit';
    documentForm: any;
    private editingDocumentId;
    readonly Math: Math;
    constructor(route: ActivatedRoute, router: Router, servicesPublicsService: ServicesPublicsService);
    ngOnInit(): void;
    initPagination(): void;
    get paginatedFrais(): Frais[];
    get paginatedDocuments(): DocumentRequis[];
    changeFraisPage(page: number): void;
    getFraisPaginationPages(): number[];
    changeDocumentsPage(page: number): void;
    getDocumentsPaginationPages(): number[];
    goBack(): void;
    onAddFrais(): void;
    onEditFrais(frais: Frais): void;
    closeFraisModal(): void;
    saveFrais(): void;
    onDeleteFrais(fraisId: number): void;
    private getEmptyFraisForm;
    onAddDocument(): void;
    onEditDocument(doc: DocumentRequis): void;
    closeDocumentModal(): void;
    saveDocument(): void;
    onDeleteDocument(docId: number): void;
    private getEmptyDocumentForm;
    showNotificationMessage(message: string, type?: 'success' | 'error' | 'info'): void;
    getFraisTypeLabel(type: string): string;
    getFrequenceLabel(frequence: string): string;
    getTotalFrais(): number;
    getCategoryColor(code: string): string;
}
//# sourceMappingURL=category-detail.component.d.ts.map