interface Transaction {
    id: string;
    type: 'depot' | 'retrait' | 'transfert' | 'paiement' | 'achat' | 'commission';
    typeLabel: string;
    montant: number;
    utilisateur: string;
    agent: string;
    date: string;
    statut: 'effectuee' | 'en_attente' | 'annulee' | 'echouee';
    description?: string;
    reference?: string;
    ip?: string;
}
interface Toast {
    id: number;
    message: string;
    type: 'success' | 'danger' | 'info' | 'warning';
}
export declare class TransactionsSettingsComponent {
    readonly title = "Gestion des Transactions";
    readonly icon = "\uD83D\uDCB8";
    readonly pageSize = 10;
    readonly currentDate: string;
    activeTab: 'toutes' | 'types' | 'filtres' | 'analytique';
    private currentPage;
    searchTerm: string;
    filterStatut: string;
    filterType: string;
    filterPeriode: string;
    selectedIds: Set<string>;
    private transactions;
    private toastSeq;
    modalOpen: boolean;
    selectedTransaction: Transaction | null;
    actionModalOpen: boolean;
    actionModalTitle: string;
    actionModalType: string;
    actionData: any;
    formData: any;
    toasts: Toast[];
    constructor();
    private initializeData;
    toggleSelection(id: string): void;
    toggleAll(event: any): void;
    isSelected(id: string): boolean;
    isAllSelected(): boolean;
    getSelectedCount(): number;
    getAllTransactions(): Transaction[];
    getTransactionsByStatut(statut: string): Transaction[];
    getMontantTotal(): number;
    getMontantMoyen(): number;
    getTypesCount(): number;
    getTransactionsEnAttente(): Transaction[];
    getTransactionsEchouees(): Transaction[];
    getStatutLabel(statut: string): string;
    getTypeClass(type: string): string;
    getAnalyticsData(): any[];
    getFilteredTransactions(): Transaction[];
    onSearchChange(): void;
    onFilterChange(): void;
    getPaginatedFilteredTransactions(): Transaction[];
    getTotalFilteredPages(): number;
    getCurrentPage(): number;
    nextPage(): void;
    previousPage(): void;
    setActiveTab(tab: 'toutes' | 'types' | 'filtres' | 'analytique'): void;
    getTypes(): any[];
    getTypeIcon(type: string): string;
    filterByType(type: string): void;
    getFiltres(): any[];
    getFilterOptions(filterType: string): string[];
    openFilter(filter: any): void;
    openTransactionDetails(transaction: Transaction): void;
    openAction(actionId: string, transaction?: Transaction): void;
    private getActionTitle;
    getActionIcon(): string;
    confirmAction(): void;
    private exportTransactions;
    private corrigerTransaction;
    private annulerTransaction;
    private annulerSelection;
    private reattribuerTransaction;
    private marquerFrauduleuse;
    private partagerTransaction;
    exportExcel(): void;
    printList(): void;
    printTransaction(): void;
    closeModal(): void;
    closeActionModal(): void;
    toast(message: string, type?: Toast['type']): void;
    dismissToast(id: number): void;
}
export {};
//# sourceMappingURL=transactions-settings.component.d.ts.map